{
  "compute_environment": "LOCAL_MACHINE",
  debug: false,
  "deepspeed_config": {
    "gradient_clipping": 1.0,
    "zero_stage": 2
  },
  "distributed_type": "DEEPSPEED",  # DEEPSPEED, MULTI_GPU
  "downcast_bf16": false,
  "enable_cpu_affinity": false,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "no",  ## 默认应该是fp16
  "num_machines": 1,  ## 几个机器
  "num_processes": 1, ## 几个GPU 
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}